# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/ProgramBasicInterface.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(709, 505)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.AlgoComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.AlgoComboBox.setGeometry(QtCore.QRect(480, 10, 221, 21))
        self.AlgoComboBox.setObjectName("AlgoComboBox")
        self.AlgoComboBox.addItem("")
        self.AlgoComboBox.addItem("")
        self.AlgoComboBox.addItem("")
        self.AlgoComboBox.addItem("")
        self.AlgoComboBox.addItem("")
        self.runButton = QtWidgets.QPushButton(self.centralwidget)
        self.runButton.setGeometry(QtCore.QRect(480, 190, 101, 31))
        self.runButton.setObjectName("runButton")
        self.labelEps = QtWidgets.QLabel(self.centralwidget)
        self.labelEps.setGeometry(QtCore.QRect(480, 40, 61, 21))
        self.labelEps.setObjectName("labelEps")
        self.labelSigma = QtWidgets.QLabel(self.centralwidget)
        self.labelSigma.setGeometry(QtCore.QRect(480, 70, 61, 21))
        self.labelSigma.setObjectName("labelSigma")
        self.labelA = QtWidgets.QLabel(self.centralwidget)
        self.labelA.setGeometry(QtCore.QRect(480, 100, 61, 21))
        self.labelA.setObjectName("labelA")
        self.labelB = QtWidgets.QLabel(self.centralwidget)
        self.labelB.setGeometry(QtCore.QRect(480, 130, 51, 21))
        self.labelB.setObjectName("labelB")
        self.labelFunc = QtWidgets.QLabel(self.centralwidget)
        self.labelFunc.setGeometry(QtCore.QRect(480, 160, 61, 21))
        self.labelFunc.setObjectName("labelFunc")
        self.lineEditFunc = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditFunc.setGeometry(QtCore.QRect(540, 160, 151, 21))
        self.lineEditFunc.setObjectName("lineEditFunc")
        self.doubleSpinBoxEps = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBoxEps.setGeometry(QtCore.QRect(540, 40, 62, 24))
        self.doubleSpinBoxEps.setDecimals(5)
        self.doubleSpinBoxEps.setObjectName("doubleSpinBoxEps")
        self.doubleSpinBoxSigma = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBoxSigma.setGeometry(QtCore.QRect(540, 70, 62, 24))
        self.doubleSpinBoxSigma.setDecimals(5)
        self.doubleSpinBoxSigma.setObjectName("doubleSpinBoxSigma")
        self.doubleSpinBox_A = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_A.setGeometry(QtCore.QRect(540, 100, 62, 24))
        self.doubleSpinBox_A.setDecimals(5)
        self.doubleSpinBox_A.setMinimum(-1000000000.0)
        self.doubleSpinBox_A.setMaximum(1000000000.0)
        self.doubleSpinBox_A.setObjectName("doubleSpinBox_A")
        self.doubleSpinBox_B = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_B.setGeometry(QtCore.QRect(540, 130, 62, 24))
        self.doubleSpinBox_B.setDecimals(5)
        self.doubleSpinBox_B.setMinimum(-1000000000.0)
        self.doubleSpinBox_B.setMaximum(1000000000.0)
        self.doubleSpinBox_B.setObjectName("doubleSpinBox_B")
        self.logTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.logTextEdit.setGeometry(QtCore.QRect(10, 10, 461, 481))
        self.logTextEdit.setObjectName("logTextEdit")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(480, 230, 221, 261))
        self.textBrowser.setObjectName("textBrowser")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.AlgoComboBox.setItemText(0, _translate("MainWindow", "Метод половинного деления"))
        self.AlgoComboBox.setItemText(1, _translate("MainWindow", "Метод золотого сечения"))
        self.AlgoComboBox.setItemText(2, _translate("MainWindow", "Метод средней точки"))
        self.AlgoComboBox.setItemText(3, _translate("MainWindow", "Метод Ньютона-Рафсона"))
        self.AlgoComboBox.setItemText(4, _translate("MainWindow", "Метод хорд"))
        self.runButton.setText(_translate("MainWindow", "Запуск"))
        self.labelEps.setText(_translate("MainWindow", "epsilon"))
        self.labelSigma.setText(_translate("MainWindow", "sigma"))
        self.labelA.setText(_translate("MainWindow", "a"))
        self.labelB.setText(_translate("MainWindow", "b"))
        self.labelFunc.setText(_translate("MainWindow", "f(x)"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:700;\">Инструкция по вводу функции</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-weight:700;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Функция вводится по правилам синтаксиса Python.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Переменная обозначается как <span style=\" font-weight:700;\">x</span>.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Допустимые операции: </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:700;\">+</span>, <span style=\" font-weight:700;\">-</span>, <span style=\" font-weight:700;\">*</span>, <span style=\" font-weight:700;\">/</span>, <span style=\" font-weight:700;\">**</span> (возведение в степень)</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Дробная часть числа пишется после символа <span style=\" font-weight:700;\">. </span>(точка)</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Для корректной работы необходимо учитывать особенности работы алгоритмов.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-style:italic;\">Примеры ввода:</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">3*x**4 + (x - 1)**2</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">2*x**2 + x + 1</p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
