# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ProgramBasicInterface.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(709, 505)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.AlgoComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.AlgoComboBox.setGeometry(QtCore.QRect(480, 10, 221, 21))
        self.AlgoComboBox.setObjectName("AlgoComboBox")
        self.AlgoComboBox.addItem("")
        self.AlgoComboBox.addItem("")
        self.AlgoComboBox.addItem("")
        self.AlgoComboBox.addItem("")
        self.AlgoComboBox.addItem("")
        self.runButton = QtWidgets.QPushButton(self.centralwidget)
        self.runButton.setGeometry(QtCore.QRect(480, 190, 101, 31))
        self.runButton.setObjectName("runButton")
        self.labelEps = QtWidgets.QLabel(self.centralwidget)
        self.labelEps.setGeometry(QtCore.QRect(480, 40, 61, 21))
        self.labelEps.setObjectName("labelEps")
        self.labelSigma = QtWidgets.QLabel(self.centralwidget)
        self.labelSigma.setGeometry(QtCore.QRect(480, 70, 61, 21))
        self.labelSigma.setObjectName("labelSigma")
        self.labelA = QtWidgets.QLabel(self.centralwidget)
        self.labelA.setGeometry(QtCore.QRect(480, 100, 61, 21))
        self.labelA.setObjectName("labelA")
        self.labelB = QtWidgets.QLabel(self.centralwidget)
        self.labelB.setGeometry(QtCore.QRect(480, 130, 51, 21))
        self.labelB.setObjectName("labelB")
        self.labelFunc = QtWidgets.QLabel(self.centralwidget)
        self.labelFunc.setGeometry(QtCore.QRect(480, 160, 61, 21))
        self.labelFunc.setObjectName("labelFunc")
        self.lineEditFunc = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditFunc.setGeometry(QtCore.QRect(540, 160, 151, 21))
        self.lineEditFunc.setObjectName("lineEditFunc")
        self.doubleSpinBoxEps = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBoxEps.setGeometry(QtCore.QRect(540, 40, 62, 24))
        self.doubleSpinBoxEps.setObjectName("doubleSpinBoxEps")
        self.doubleSpinBoxSigma = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBoxSigma.setGeometry(QtCore.QRect(540, 70, 62, 24))
        self.doubleSpinBoxSigma.setObjectName("doubleSpinBoxSigma")
        self.doubleSpinBox_A = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_A.setGeometry(QtCore.QRect(540, 100, 62, 24))
        self.doubleSpinBox_A.setObjectName("doubleSpinBox_A")
        self.doubleSpinBox_B = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_B.setGeometry(QtCore.QRect(540, 130, 62, 24))
        self.doubleSpinBox_B.setObjectName("doubleSpinBox_B")
        self.logTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.logTextEdit.setGeometry(QtCore.QRect(10, 10, 461, 481))
        self.logTextEdit.setObjectName("logTextEdit")
        self.plotButton = QtWidgets.QPushButton(self.centralwidget)
        self.plotButton.setGeometry(QtCore.QRect(590, 190, 101, 31))
        self.plotButton.setObjectName("plotButton")
        self.reportButton = QtWidgets.QPushButton(self.centralwidget)
        self.reportButton.setGeometry(QtCore.QRect(480, 230, 101, 31))
        self.reportButton.setObjectName("reportButton")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.AlgoComboBox.setItemText(0, _translate("MainWindow", "Метод половинного деления"))
        self.AlgoComboBox.setItemText(1, _translate("MainWindow", "Метод золотого сечения"))
        self.AlgoComboBox.setItemText(2, _translate("MainWindow", "Метод средней точки"))
        self.AlgoComboBox.setItemText(3, _translate("MainWindow", "Метод Ньютона-Рафсона"))
        self.AlgoComboBox.setItemText(4, _translate("MainWindow", "Метод хорд"))
        self.runButton.setText(_translate("MainWindow", "Запуск"))
        self.labelEps.setText(_translate("MainWindow", "epsilon"))
        self.labelSigma.setText(_translate("MainWindow", "sigma"))
        self.labelA.setText(_translate("MainWindow", "a"))
        self.labelB.setText(_translate("MainWindow", "b"))
        self.labelFunc.setText(_translate("MainWindow", "f(x)"))
        self.plotButton.setText(_translate("MainWindow", "График"))
        self.reportButton.setText(_translate("MainWindow", "Отчет"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
